<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <OutputType>WinExe</OutputType>
    <StartupObject>UltraClick.Program</StartupObject><AssemblyName>UltraClick</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Drawing" /><Reference Include="System.Windows.Forms" />
    <Compile Include="Program.cs" /><Compile Include="EngineTests.cs" /><Compile Include="LiveReceiver.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>


